
### Creamos nuevo usuarios
POST http://localhost:7777/api/v1/user
Content-Type: application/json
Accept: application/json

{
  "ciuser": "758476343",
  "firstName": "Ramon",
  "lastName": "Valdez",
  "email": "rvaldez@gmail.com",
  "fono": "65739875",
  "username": "rvaldez",
  "secret" : "12345"
}


### Obtener usuario por correo
GET http://localhost:7777/api/v1/user/email/aguilar.cristhiian@gmail.com


### Consultamos el usuario autenticado por token, sin secret
GET http://localhost:7777/api/v1/user/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtdGFuY2FyYSIsImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njg5OTA2NDh9.UG8HKMVgIFRJ927QktMFXOwNixLmd1OBKX6Zn6FEOtg